# Generated by Django 3.0 on 2019-12-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_owner',
            new_name='product_owner',
        ),
    ]
