# Generated by Django 3.0 on 2020-01-28 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191229_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
