# Generated by Django 2.2.6 on 2019-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191024_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='time_spent',
            field=models.FloatField(default=0),
        ),
    ]
