# Generated by Django 2.2.6 on 2019-10-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_client_time_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
