# Generated by Django 3.0 on 2020-01-29 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200128_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(default='client-name'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 8, 42, 30, 748480)),
        ),
    ]
