# Generated by Django 3.0 on 2020-02-27 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200128_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 7, 25, 12, 218680)),
        ),
    ]
