# Generated by Django 2.2.6 on 2019-10-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191025_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project_owner',
            field=models.CharField(default='No owner', max_length=100, verbose_name='Project Owner'),
        ),
    ]
