# Generated by Django 3.0 on 2020-01-31 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200129_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(default='Location', max_length=500, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(default='client-slug'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 18, 55, 52, 690370)),
        ),
    ]
