# Generated by Django 3.0 on 2019-12-17 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_client_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='extra_hours',
        ),
        migrations.CreateModel(
            name='ClientTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftover_hours', models.IntegerField(default=0)),
                ('extra_hours', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Client')),
            ],
        ),
    ]
