# Generated by Django 3.0 on 2020-01-31 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200131_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 18, 58, 7, 766025)),
        ),
    ]
