# Generated by Django 3.0 on 2020-01-31 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200131_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ticketing_system',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Ticketing System'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 19, 23, 25, 577664)),
        ),
    ]
