# Generated by Django 3.0 on 2019-12-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191217_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttime',
            name='id',
        ),
        migrations.AlterField(
            model_name='clienttime',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Client'),
        ),
    ]
