# Generated by Django 3.0.2 on 2020-02-03 20:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200131_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 20, 32, 37, 218308)),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 3, 20, 32, 37, 217753))),
                ('description', models.TextField(default='')),
                ('priority', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('subject', models.CharField(default='Subject', max_length=500, verbose_name='Subject')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Client')),
            ],
        ),
    ]
