# Generated by Django 3.0.2 on 2020-02-03 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200203_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='client_id',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 20, 54, 31, 970456)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 20, 54, 31, 971058)),
        ),
    ]
