# Generated by Django 3.0.2 on 2020-02-04 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200203_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
