# Generated by Django 3.0 on 2020-02-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200204_0751'),
        ('dashboard', '0004_auto_20200227_0725'),
    ]

    operations = [
    ]
