# Generated by Django 3.0.3 on 2020-03-14 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_merge_20200228_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='attendable_version',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Attendable Version'),
        ),
        migrations.AddField(
            model_name='client',
            name='baseproject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='onsale_version',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Onsale Version'),
        ),
        migrations.AddField(
            model_name='client',
            name='wp_version',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Wordpress Version'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='import_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
