# Generated by Django 3.0.3 on 2020-12-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200314_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='availability_sync',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Availability Sync'),
        ),
        migrations.AddField(
            model_name='client',
            name='event_sync',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Events and Instances Sync'),
        ),
    ]
